{% set version = '0.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-infer
  version: {{ version|replace("-", "_") }}

source:
  fn: infer_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/infer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/infer/infer_{{ version }}.tar.gz
  sha256: c29e4927e67cb955340f069b9847d6a431b9f47c7d6fea687edacfd673a4f907

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.7.0
    - r-tibble
    - r-rlang >=0.2.0
    - r-ggplot2
    - r-magrittr
    - r-glue >=1.3.0
  run:
    - r-base
    - r-dplyr >=0.7.0
    - r-tibble
    - r-rlang >=0.2.0
    - r-ggplot2
    - r-magrittr
    - r-glue >=1.3.0

test:
  commands:
    - $R -e "library('infer')"           # [not win]
    - "\"%R%\" -e \"library('infer')\""  # [win]

about:
  home: https://github.com/tidymodels/infer
  license: CC0
  summary: 'The objective of this package is to perform inference using an expressive statistical
    grammar that coheres with the tidy design framework. '
  license_family: CC

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
