{% set version = '0.4.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-infer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/infer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/infer/infer_{{ version }}.tar.gz
  sha256: 3601cce61059252525503ad4ce546d432f3383623ea583fca2d7a15cf70f8b4e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.7.0
    - r-ggplot2
    - r-glue >=1.3.0
    - r-magrittr
    - r-rlang >=0.2.0
    - r-tibble
  run:
    - r-base
    - r-dplyr >=0.7.0
    - r-ggplot2
    - r-glue >=1.3.0
    - r-magrittr
    - r-rlang >=0.2.0
    - r-tibble

test:
  commands:
    - $R -e "library('infer')"           # [not win]
    - "\"%R%\" -e \"library('infer')\""  # [win]

about:
  home: https://github.com/tidymodels/infer
  license: CC0
  summary: 'The objective of this package is to perform inference using an expressive statistical
    grammar that coheres with the tidy design framework. '
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: infer
# Type: Package
# Title: Tidy Statistical Inference
# Version: 0.4.0.1
# Authors@R: c( person("Andrew", "Bray", email = "abray@reed.edu", role = c("aut", "cre")), person("Chester", "Ismay", email = "chester.ismay@gmail.com", role = "aut"), person("Ben", "Baumer", email = "ben.baumer@gmail.com", role = "aut"), person("Mine", "Cetinkaya-Rundel", email = "mine@stat.duke.edu", role = "aut"), person("Evgeni", "Chasnovski", email = "evgeni.chasnovski@gmail.com", role = "ctb"), person("Ted", "Laderas", email = "tedladeras@gmail.com", role = "ctb"), person("Nick", "Solomon", email = "nick.solomon@datacamp.com", role = "ctb"), person("Johanna", "Hardin", email = "Jo.Hardin@pomona.edu", role = "ctb"), person("Albert Y.", "Kim", email = "albert.ys.kim@gmail.com", role = "ctb"), person("Neal", "Fultz", email = "nfultz@gmail.com", role = "ctb"), person("Doug", "Friedman", email = "doug.nhp@gmail.com", role = "ctb"), person("Richie", "Cotton", email = "richie@datacamp.com", role = "ctb"), person("Brian", "Fannin", email = "captain@pirategrunt.com", role = "ctb"))
# Description: The objective of this package is to perform inference using an expressive statistical grammar that coheres with the tidy design framework.
# License: CC0
# Encoding: UTF-8
# LazyData: true
# Imports: dplyr (>= 0.7.0), methods, tibble, rlang (>= 0.2.0), ggplot2, magrittr, glue (>= 1.3.0), grDevices
# Depends: R (>= 3.1.2)
# Suggests: broom, devtools (>= 1.12.0), knitr, rmarkdown, nycflights13, stringr, testthat, covr
# URL: https://github.com/tidymodels/infer
# BugReports: https://github.com/tidymodels/infer/issues
# RoxygenNote: 6.1.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-04-21 09:26:45 UTC; ripley
# Author: Andrew Bray [aut, cre], Chester Ismay [aut], Ben Baumer [aut], Mine Cetinkaya-Rundel [aut], Evgeni Chasnovski [ctb], Ted Laderas [ctb], Nick Solomon [ctb], Johanna Hardin [ctb], Albert Y. Kim [ctb], Neal Fultz [ctb], Doug Friedman [ctb], Richie Cotton [ctb], Brian Fannin [ctb]
# Maintainer: Andrew Bray <abray@reed.edu>
# Repository: CRAN
# Date/Publication: 2019-04-22 06:58:08 UTC
