appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: JRJjo2WDsehIQ4g5p4Xgql77qGbOlvsoDYN3Yd0Hss+LdTXLJgOJFW5HKTBqxkGmMkBSNlrwNwXrA5WBQtsOGD3dwjl4eGVmmDJStuL9aJ5jQ99XWpNZd2KmjrOPVvgs3HvimbhEL5BSb6WK11HuNXQN/9eFMhTe5SwngW90sGroyXYDjwkvQQZkb4whYuJAFaKw2bv662QdtLRNM9tj0M4MRUZXIk4hDeCqSuLYf+ps20yT9x3LV1WZkWjBFwP5X/VuICeEUXBRQCnmV4asRtwqYOJBqJBWUHRr2SspEdxdJVpWb6QA3FYAge0mivLnKVh+plUajVQevvS4/jRKuIyDsNp1Yerq2DKPvgLyFsUf6e5L3TBrqz/iFQtaLoF8E8oRpE5HEmIYtCN3ckO2YFyiiGuwdTv8r9jnupfHvirVGedy/VEPaGEHjcAXbQ2xrisiCN3+OkWAj4Dk8yVeaLtDiMgIDTxvlGhXYhKytJn0FZOFpqY7yuYbI9gbUyv02H6M+UbqmngxbvHqIOYNSk2+rjSUtRZ7oIPAZgsbjx60pOSlaYDPXvICkDU7GWVwKv6vb8WFqaai6oxkYxaoUmknbBtUEo2O5AWWF379Fr81owe6nxtk1t4Qrl7FhPF2TyzaT8X4qjRqEHtVXO+Zzlxt23OnNH8J7sD7SVYkTRI=}
